baseURL = 'https://www.marcdougherty.com'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = "Marc's Blog"
enableEmoji = true
enableGitInfo = true
googleAnalytics = 'G-31G86DYMCL'

[frontmatter]
date = [':filename', 'date', 'publishDate', ':git', 'lastmod']
lastmod = ['lastmod', ':git', 'date']

[permalink]
posts = '/:year/:month/:title/'

[outputs]
  home = ["HTML", "RSS", "JSON"]

