baseURL = 'https://muncus.github.io'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = "Marc's Blog"
enableEmoji = true
canonicalizeURL = true
enableGitInfo = true
# TODO: googleAnalytics

[frontmatter]
date = ['date', ':git', ':fileModTime', ':default']
lastmod = [':git']

[permalink]
posts = '/:year/:month/:title/'
