baseURL = 'https://www.marcdougherty.com'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = "Marc's Blog"
enableEmoji = true
enableGitInfo = true
googleAnalytics = 'G-31G86DYMCL'

[frontmatter]
date = [':filename', 'date', 'publishDate', ':git', ':fileModTime']
lastmod = ['lastmod', ':git', 'date', ':fileModTime' ]

[permalinks.page]
  posts = '/:year/:slug/'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = 'tags'
  category = 'categories'
  series = "series"
