title = "Marc Dougherty"
dateFormat = "2006-01-02"

[author]
name = "Marc Dougherty"
# image = "img/author.jpg"
headline = "Socio-technical systems engineer"
bio = "Developer, SRE, Artist, and Father."
links = [
  { github = "https://github.com/muncus" },
  { twitter = "https://twitter.com/muncus" },
  { dev = "https://dev.to/muncus" },
  { medium = "https://medium.com/@muncus" }
]

