name: Marc Dougherty
tagline: "⚒ ⚙ ⛵ "
analytics_tag: "UA-12978603-2"
permalink: none

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false


# resume things.
resume_name: 'Marc Dougherty'
email: 'marc@marcdougherty.com'
github_username: 'muncus'
twitter_username: 'muncus'
linkedin_username: 'doughertymarc'

defaults:
  -
    scope:
      path: "" #Empty scope applies to all.
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" #Empty scope applies to all.
    values:
      layout: "stock"

exclude: [
  '_config.yml',
  'CNAME',
  '.git',
  '.gitignore',
  'TODO',
]

gems:
  - jekyll-feed
  - jemoji
