name: Marc Dougherty
tagline: "⚒ ⚙ ⛵ "
analytics_tag: "UA-12978603-2"
markdown: redcarpet
permalink: none

defaults:
  -
    scope:
      path: "" #Empty scope applies to all.
    values: 
      layout: stock
